#!/bin/sh


# decalring empty assosiative array
declare -A FILES

#function to get files state
function getFiles() {
    
    #naming each flag
    case $1 in
        "-o") 
            state="untracked"
            ;;
        "-d")
            state="deleted"
            ;;
        "-m")
            state="modified"
            ;;
        "-c")
            state="cached"
            ;;
        *)
            state="unknown"
            ;;
    esac

    # getting list of files according to flags
    ST=$(git ls-files $1)

    files=()
    for f in $ST
    do
        files+=($f)
    done

    #assosiative array with keys as files states and values and list of files
    FILES+=([$state]=${files[@]})
}

getFiles "-o"
getFiles "-m"
getFiles "-d"

#echo all files with their states on shell
for key in "${!FILES[@]}"
do
    echo "$key => ${FILES[$key]}"
done


